### ISSUE TITLE
Store `api_key` as Environment Variable

### ISSUE THREAD

**Issue by nicholaswilde** [wakatime/wakatime-cli#761]
Is it possible to store the `api_key` listed in `.wakatime.cfg` file as an environmental variable instead? Perhaps something like `WAKATIME_API_KEY`. This would help by being able to create backups of my encrypted bash exports file.

**Comment by gandarez** [comment]
@alanhamlett would you agree that some editors and the cli could read `WAKATIME_API_KEY` env var?

**Comment by gandarez** [comment]
@nicholaswilde sorry being so late replying you. Are you still wanting this feature? We already implemented a way you can import any config file over already loaded wakatime one. Does that help you achieving what you want?

https://github.com/wakatime/wakatime-cli/issues/464
https://github.com/wakatime/wakatime-cli/pull/702

**Comment by alanhamlett** [comment]
Closing as solved by including config files so you can backup the main config without api key.

**Comment by alanhamlett** [comment]
I recently found [this blog post](https://medium.com/@verbruggenalex/removing-a-recurring-annoyance-with-gitpod-and-wakatime-92a809e195b5) explaining a use case for the `WAKATIME_API_KEY` env var that's not solved with recursive config files. I'll submit a PR to support loading api key from this env var.
